[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ancient-greek-backend-eee"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
    "greek-inflexion-eee @ git+https://codeberg.org/EEE-project/greek-inflexion-eee.git",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "eee @ git+https://codeberg.org/EEE-project/eee.git",
]

[project.entry-points."eee.backends.v1"]
grc = "ancient_greek_backend_eee:AncientGreekBackend"

[tool.hatch.build.targets.wheel]
packages = ["src/ancient_greek_backend_eee"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
testpaths = ["tests"]
