[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ancient-greek-backend-eee"
version = "0.7.4"
requires-python = ">=3.12"
dependencies = [
    "greek-inflexion-eee @ git+https://codeberg.org/EEE-project/greek-inflexion-eee.git",
]

[dependency-groups]
dev = [
    "pytest",
    "eee-project @ git+https://codeberg.org/EEE-project/eee-project.git",
]

[project.entry-points."eee_project.backends.v1"]
grc = "ancient_greek_backend_eee:AncientGreekBackend"

[project.entry-points."eee_project.named_backends.v1"]
ancient-greek = "ancient_greek_backend_eee:AncientGreekBackend"

[tool.hatch.build.targets.wheel]
packages = ["src/ancient_greek_backend_eee"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
testpaths = ["tests"]
